/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_Matrix */

#ifndef _Included_com_company_Matrix
#define _Included_com_company_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_Matrix
 * Method:    multiplyC
 * Signature: ([D[D[DIII)V
 */
JNIEXPORT void JNICALL Java_com_company_Matrix_multiplyC
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
